ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "aiSuggestedHourlyRate" DOUBLE PRECISION;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "configuredHourlyRate" DOUBLE PRECISION;
ALTER TABLE "QuoteItem" ADD COLUMN IF NOT EXISTS "rateSource" TEXT;
